Parameters:
  DBAdmin:
    Description: parameters of admin user
    Type: String
  DBAnalyst:
    Description: parameters of read only analyst user
    Type: String
  FunctionVersion:
    Description: version of function zip in s3
    Type: String
  FunctionBucket:
    Description: bucket name of where functions zip lives
    Type: String

Resources:
  #ETLBucket:
  #ParquetBucket:
  #  Type: AWS::S3::Bucket
  #  Properties:
  #    BucketName: !Sub "${AWS::StackName}-${AWS::Region}"
  LambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.10
      Content:
        S3Bucket: !Ref FunctionBucket 
        S3Key: lambda_layer.zip
  LoadSalesRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
  #ETLRole:
  #  Type: AWS::IAM::Role
  #  Properties:
  #    AssumeRolePolicyDocument:
  #      Version: "2012-10-17"
  #      Statement:
  #        - Effect: "Allow"
  #          Principal:
  #            Service:
  #              - glue.amazonaws.com
  #          Action:
  #            - "sts:AssumeRole"
  #    Policies:
  #      - PolicyName: etl-policy
  #        PolicyDocument:
  #          Version: "2012-10-17"
  #          Statement:
  #            - Effect: "Allow"
  #              Action: "s3:GetObject"
  #              Resource: !GetAtt ETLBucket.Arn
  #            - Effect: "Allow"
  #              Action: "s3:PutObject"
  #              Resource: !GetAtt ETLBucket.Arn
  #            - Effect: "Allow"
  #              Action: "s3:ListBucket"
  #              Resource: !GetAtt ETLBucket.Arn
  #            - Effect: "Allow"
  #              Action: "logs:*"
  #              Resource: "arn:aws:logs:*:*:*"
  LoadSalesFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: load_sales.handler
      Role: !GetAtt LoadSalesRole.Arn
      Environment:
        Variables:
          DB_ADMIN: !Ref DBAdmin
      Code:
        S3Bucket: !Ref FunctionBucket
        S3Key: tradewind_functions.zip
        S3ObjectVersion: !Ref FunctionVersion
      Runtime: python3.10
      Timeout: 60
      Layers:
        - !Ref LambdaLayer
  LoadSalesLog:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${LoadSalesFunction}"
      RetentionInDays: 5
  LoadSalesRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Description of the rule
      ScheduleExpression: cron(0 12 * * ? *)
      State: ENABLED
      Targets:
        - Arn: !GetAtt LoadSalesFunction.Arn
          Id: Target0
  LoadEventPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt LoadSalesFunction.Arn
      Principal: events.amazonaws.com
      SourceArn: !GetAtt LoadSalesRule.Arn
